"""corregir contraseña name

Revision ID: 1b757b07d16e
Revises: 
Create Date: 2025-02-21 19:54:58.958362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b757b07d16e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Animales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sexo', sa.String(length=10), nullable=False),
    sa.Column('marca', sa.String(length=10), nullable=False),
    sa.Column('edad', sa.Integer(), nullable=False),
    sa.Column('raza', sa.String(length=100), nullable=False),
    sa.Column('peso', sa.Float(), nullable=False),
    sa.Column('proposito', sa.String(length=100), nullable=False),
    sa.Column('fechaNacimiento', sa.Date(), nullable=False),
    sa.Column('lote', sa.String(length=50), nullable=False),
    sa.Column('cantidadPartos', sa.Integer(), nullable=True),
    sa.Column('fechaUltimoParto', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('insumos',
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('unidadDeMedida', sa.String(length=50), nullable=False),
    sa.Column('valorUnitario', sa.Float(), nullable=False),
    sa.Column('stockMinimo', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('descripcion')
    )
    with op.batch_alter_table('DatosUsuarios', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.alter_column('correo',
               existing_type=sa.NVARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.alter_column('contrasena',
               existing_type=sa.VARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=255),
               nullable=False)
        batch_op.alter_column('rol',
               existing_type=sa.VARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=50),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('DatosUsuarios', schema=None) as batch_op:
        batch_op.alter_column('rol',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
        batch_op.alter_column('contrasena',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
        batch_op.alter_column('correo',
               existing_type=sa.String(length=100),
               type_=sa.NVARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
        batch_op.alter_column('nombre',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)

    op.drop_table('insumos')
    op.drop_table('Animales')
    # ### end Alembic commands ###
