"""Agregar campo eliminado a Animal

Revision ID: 6991a9df5b97
Revises: 764c52a10348
Create Date: 2025-02-25 22:06:53.380351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6991a9df5b97'
down_revision = '764c52a10348'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Animales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eliminado', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Animales', schema=None) as batch_op:
        batch_op.drop_column('eliminado')

    # ### end Alembic commands ###
