"""Corrigiendo modelo de usuario

Revision ID: 741d4c01aba4
Revises: c197c75b0153
Create Date: 2025-02-21 19:10:26.513938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '741d4c01aba4'
down_revision = 'c197c75b0153'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('correo', sa.String(length=100), nullable=False),
    sa.Column('contraseña', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo')
    )
    op.create_table('insumos',
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('unidadDeMedida', sa.String(length=50), nullable=False),
    sa.Column('valorUnitario', sa.Float(), nullable=False),
    sa.Column('stockMinimo', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('descripcion')
    )
    op.drop_table('insumo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insumo',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('descripcion', sa.VARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('cantidad', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('unidadDeMedida', sa.VARCHAR(length=10, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('valorUnitario', sa.FLOAT(precision=53), autoincrement=False, nullable=True),
    sa.Column('stockMinimo', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='PK__insumo__3213E83F45474150')
    )
    op.drop_table('insumos')
    op.drop_table('Usuarios')
    # ### end Alembic commands ###
