"""Agregar tabla AnimalesEliminados

Revision ID: 764c52a10348
Revises: b8874db844c5
Create Date: 2025-02-25 17:14:02.841776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '764c52a10348'
down_revision = 'b8874db844c5'
branch_labels = None
depends_on = None


def upgrade():
    # Primero elimina la tabla antigua
    #op.drop_table('AnimalesEliminados')
    
    # Luego crea la nueva tabla con el nombre correcto
    op.create_table('animales_eliminados',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('raza', sa.String(length=50), nullable=False),
        sa.Column('edad', sa.Integer(), nullable=False),
        sa.Column('peso', sa.Float(), nullable=False),
        sa.Column('sexo', sa.String(length=10), nullable=False),
        sa.Column('marca', sa.String(length=10), nullable=False),
        sa.Column('proposito', sa.String(length=20), nullable=False),
        sa.Column('fechaNacimiento', sa.Date(), nullable=False),
        sa.Column('lote', sa.String(length=20), nullable=False),
        sa.Column('cantidadPartos', sa.Integer(), nullable=True),
        sa.Column('fechaUltimoParto', sa.Date(), nullable=True),
        sa.Column('fecha_eliminacion', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AnimalesEliminados',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('raza', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('edad', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('peso', sa.FLOAT(precision=53), autoincrement=False, nullable=True),
    sa.Column('sexo', sa.VARCHAR(length=10, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('marca', sa.VARCHAR(length=10, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('proposito', sa.VARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('fechaNacimiento', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('lote', sa.VARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('cantidadPartos', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fechaUltimoParto', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('fechaEliminacion', sa.DATETIME(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='PK_AnimalesEliminados')
    )
    op.drop_table('animales_eliminados')
    # ### end Alembic commands ###
