"""Inicializando base de datos AgroControl

Revision ID: b8874db844c5
Revises: 
Create Date: 2025-02-23 21:18:06.417621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8874db844c5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Animales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sexo', sa.String(length=10), nullable=False),
    sa.Column('marca', sa.String(length=10), nullable=False),
    sa.Column('edad', sa.Integer(), nullable=False),
    sa.Column('raza', sa.String(length=100), nullable=False),
    sa.Column('peso', sa.Float(), nullable=False),
    sa.Column('proposito', sa.String(length=100), nullable=False),
    sa.Column('fechaNacimiento', sa.Date(), nullable=False),
    sa.Column('lote', sa.String(length=50), nullable=False),
    sa.Column('cantidadPartos', sa.Integer(), nullable=True),
    sa.Column('fechaUltimoParto', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('DatosUsuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('correo', sa.String(length=100), nullable=False),
    sa.Column('contrasena', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo')
    )
    op.create_table('insumos',
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('unidadDeMedida', sa.String(length=50), nullable=False),
    sa.Column('valorUnitario', sa.Float(), nullable=False),
    sa.Column('stockMinimo', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('descripcion')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('insumos')
    op.drop_table('DatosUsuarios')
    op.drop_table('Animales')
    # ### end Alembic commands ###
