"""Inicializando migraciones

Revision ID: c197c75b0153
Revises: 
Create Date: 2025-02-19 19:39:50.361080

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = 'c197c75b0153'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Animales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sexo', sa.String(length=10), nullable=False),
    sa.Column('marca', sa.String(length=10), nullable=False),
    sa.Column('edad', sa.Integer(), nullable=False),
    sa.Column('raza', sa.String(length=100), nullable=False),
    sa.Column('peso', sa.Float(), nullable=False),
    sa.Column('proposito', sa.String(length=100), nullable=False),
    sa.Column('fechaNacimiento', sa.Date(), nullable=False),
    sa.Column('lote', sa.String(length=50), nullable=False),
    sa.Column('cantidadPartos', sa.Integer(), nullable=True),
    sa.Column('fechaUltimoParto', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('insumo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('descripcion', sa.String(length=20), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('unidadDeMedida', sa.String(length=10), nullable=False),
    sa.Column('valorUnitario', sa.Float(), nullable=True),
    sa.Column('stockMinimo', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Insumos')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Insumos',
    sa.Column('descripcion', sa.VARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('cantidad', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('unidadDeMedida', sa.VARCHAR(length=10, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('valorUnitario', mssql.MONEY(), autoincrement=False, nullable=True),
    sa.Column('stockMinimo', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.drop_table('insumo')
    op.drop_table('Animales')
    # ### end Alembic commands ###
